# Generated by Django 5.2.3 on 2025-07-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemDilemaCriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('USUARIO', 'Usuário'), ('IA', 'IA')], max_length=7, verbose_name='Remetente')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('dilema_criado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='app.dilemacriado', verbose_name='Dilema Criado')),
            ],
            options={
                'verbose_name': 'Mensagem de Dilema Criado',
                'verbose_name_plural': 'Mensagens de Dilemas Criados',
                'ordering': ['timestamp'],
            },
        ),
    ]
